import { library, dom } from "@fortawesome/fontawesome-svg-core";
import {
    faUndo,
    faTrash,
    faCheck,
    faRedo,
    faMousePointer,
    faPencilAlt,
    faEraser,
    faImage,
    faFont,
    faSave,
    faUpload,
    faDownload,
    faShareSquare,
    faAngleLeft,
    faAngleUp,
    faAngleDown,
    faAngleRight,
    faSortDown,
    faExpandArrowsAlt,
    faLock,
    faLockOpen,
    faInfoCircle,
    faSlidersH,
} from "@fortawesome/free-solid-svg-icons";
import {
    faSquare,
    faCircle,
    faFile,
    faFileAlt,
    faPlusSquare,
} from "@fortawesome/free-regular-svg-icons";

library.add(
    faUndo,
    faTrash,
    faCheck,
    faRedo,
    faMousePointer,
    faPencilAlt,
    faEraser,
    faImage,
    faFont,
    faSave,
    faUpload,
    faDownload,
    faShareSquare,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faAngleDown,
    faSortDown,
    faExpandArrowsAlt,
    faSquare,
    faCircle,
    faFile,
    faFileAlt,
    faPlusSquare,
    faLock,
    faLockOpen,
    faInfoCircle,
    faSlidersH
);

dom.i2svg();
